### Login to get JWT Token
# @name login
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@villagkart.com",
  "password": "admin123"
}

### 

@token = {{login.response.body.data.token}}

### Get All Categories
GET http://localhost:5000/api/v1/master-data/categories
Authorization: Bearer {{token}}

### Create a Category
POST http://localhost:5000/api/v1/master-data/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Raw Materials",
  "description": "Ingredients for packing"
}

### Get All Products (With pagination and search)
GET http://localhost:5000/api/v1/master-data/products?page=1&limit=5
Authorization: Bearer {{token}}

### Get Production Yield Report
GET http://localhost:5000/api/v1/master-data/reports/yield?startDate=2024-01-01&endDate=2026-12-31
Authorization: Bearer {{token}}
